/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const SubjectId = IDL.Nat;
export const TopicId = IDL.Nat;
export const Subject = IDL.Record({ 'id' : SubjectId, 'name' : IDL.Text });
export const Topic = IDL.Record({
  'id' : TopicId,
  'title' : IDL.Text,
  'subjectId' : SubjectId,
  'notes' : IDL.Text,
});

export const idlService = IDL.Service({
  'addSubject' : IDL.Func([IDL.Text], [SubjectId], []),
  'addTopic' : IDL.Func([SubjectId, IDL.Text, IDL.Text], [TopicId], []),
  'listSubjects' : IDL.Func([], [IDL.Vec(Subject)], ['query']),
  'listTopicsForSubject' : IDL.Func([SubjectId], [IDL.Vec(Topic)], ['query']),
  'removeSubject' : IDL.Func([SubjectId], [], []),
  'removeTopic' : IDL.Func([TopicId], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const SubjectId = IDL.Nat;
  const TopicId = IDL.Nat;
  const Subject = IDL.Record({ 'id' : SubjectId, 'name' : IDL.Text });
  const Topic = IDL.Record({
    'id' : TopicId,
    'title' : IDL.Text,
    'subjectId' : SubjectId,
    'notes' : IDL.Text,
  });
  
  return IDL.Service({
    'addSubject' : IDL.Func([IDL.Text], [SubjectId], []),
    'addTopic' : IDL.Func([SubjectId, IDL.Text, IDL.Text], [TopicId], []),
    'listSubjects' : IDL.Func([], [IDL.Vec(Subject)], ['query']),
    'listTopicsForSubject' : IDL.Func([SubjectId], [IDL.Vec(Topic)], ['query']),
    'removeSubject' : IDL.Func([SubjectId], [], []),
    'removeTopic' : IDL.Func([TopicId], [], []),
  });
};

export const init = ({ IDL }) => { return []; };