/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Subject { 'id' : SubjectId, 'name' : string }
export type SubjectId = bigint;
export interface Topic {
  'id' : TopicId,
  'title' : string,
  'subjectId' : SubjectId,
  'notes' : string,
}
export type TopicId = bigint;
export interface _SERVICE {
  'addSubject' : ActorMethod<[string], SubjectId>,
  'addTopic' : ActorMethod<[SubjectId, string, string], TopicId>,
  'listSubjects' : ActorMethod<[], Array<Subject>>,
  'listTopicsForSubject' : ActorMethod<[SubjectId], Array<Topic>>,
  'removeSubject' : ActorMethod<[SubjectId], undefined>,
  'removeTopic' : ActorMethod<[TopicId], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];